/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Servis ayakta mı */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bağımlılıklar hazır mı */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tanımlı rapor tipleri
         * @description Her kayıt bir 'dataset pack'. Yeni bir rapor tipi eklemek için motora, endpoint'lere veya AI katmanına dokunmak gerekmez -- yalnızca yeni bir pack tanımlanıp buraya kaydedilir.
         */
        get: operations["packs_api_v1_packs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Yüklenmiş veri setleri */
        get: operations["list_datasets_api_v1_datasets_get"];
        put?: never;
        /** CSV yükle ve işle */
        post: operations["upload_dataset_api_v1_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Veri seti özeti */
        get: operations["get_dataset_api_v1_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        /** Veri setini sil */
        delete: operations["delete_dataset_api_v1_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Veri kalitesi raporu
         * @description Tespit edilen her sorun; ağırlığı, kaç satırı etkilediği ve **ne yapıldığı** (onarildi / turetildi / silindi / karantina / isaretlendi) ile birlikte.
         */
        get: operations["get_quality_api_v1_datasets__dataset_id__quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard özeti */
        get: operations["get_overview_api_v1_datasets__dataset_id__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dönemsel trend ve değişim verisi */
        get: operations["get_periods_api_v1_datasets__dataset_id__periods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kayıt bazında özet ve zaman serisi */
        get: operations["get_entities_api_v1_datasets__dataset_id__entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk sicili */
        get: operations["get_risks_api_v1_datasets__dataset_id__risks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/analysis/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analiz hazır mı, kaç çağrı gerekecek
         * @description Frontend'in 'analiz üret' butonunu maliyet uyarısıyla göstermesi için. Önbellekte varsa çağrı yapılmayacağını bildirir.
         */
        get: operations["analysis_status_api_v1_datasets__dataset_id__analysis_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dönemsel analiz + yönetici özeti üret
         * @description Her dönem için paralel bir AI çağrısı, ardından tek bir sentez çağrısı. Sonuç önbelleğe yazılır; aynı veri seti için tekrar çağrıldığında AI'a gidilmez. `refresh=true` ile yeniden üretilebilir.
         */
        post: operations["create_analysis_api_v1_datasets__dataset_id__analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Veri üzerinde serbest soru-cevap
         * @description Model SQL yazmaz: hesaplanmış tabloları yorumlar. Böylece 'AI sayı hesaplamaz' kuralı soru-cevapta da korunur ve her yanıt kanıt taşır.
         */
        post: operations["ask_api_v1_datasets__dataset_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/report.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paylaşılabilir yönetici raporu (PDF)
         * @description KPI'lar, dönemsel trend, risk sicili ve veri kalitesi notları. AI analizi önbellekte varsa yönetici özeti ve döneme özgü aksiyonlar da eklenir; yoksa rapor yalnızca hesaplanmış verilerle üretilir ve AI çağrısı yapılmaz.
         */
        get: operations["download_report_api_v1_datasets__dataset_id__report_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Action
         * @description Somut, sahiplenilebilir bir aksiyon onerisi.
         */
        Action: {
            /**
             * Priority
             * @enum {string}
             */
            priority: "kritik" | "yuksek" | "orta" | "dusuk";
            /**
             * Title
             * @description Tek cumlelik, emir kipinde eylem basligi.
             */
            title: string;
            /**
             * Rationale
             * @description Neden simdi ve neden bu urun/kayit icin.
             */
            rationale: string;
            /**
             * Evidence
             * @description Bu aksiyonu dogrulayan, tablolardan alinmis sayilar.
             */
            evidence: components["schemas"]["Evidence"][];
            /**
             * Owner
             * @description Sorumlu departman.
             */
            owner: string;
            /**
             * Horizon
             * @enum {string}
             */
            horizon: "bu_hafta" | "bu_ay" | "bu_ceyrek";
            /**
             * Expected Impact Tl
             * @description Parasal etki tahmini; hesaplanamiyorsa bos birak.
             */
            expected_impact_tl?: number | null;
        };
        /** AnalysisResponse */
        AnalysisResponse: {
            /** Dataset Id */
            dataset_id: string;
            /** Pack Key */
            pack_key: string;
            /** Model */
            model: string;
            /**
             * Cached
             * @description True ise sonuç önbellekten geldi; yeni AI çağrısı yapılmadı.
             */
            cached: boolean;
            /** Cached At */
            cached_at?: string | null;
            /** Periods */
            periods: components["schemas"]["PeriodAnalysis"][];
            summary: components["schemas"]["ExecutiveSummary"] | null;
            grounding: components["schemas"]["GroundingOut"];
            telemetry: components["schemas"]["TelemetryOut"];
            /** Failed Periods */
            failed_periods?: {
                [key: string]: string;
            }[];
        };
        /** AnalysisStatusResponse */
        AnalysisStatusResponse: {
            /** Dataset Id */
            dataset_id: string;
            /** Ai Configured */
            ai_configured: boolean;
            /** Cached */
            cached: boolean;
            /** Model */
            model: string;
            /** Effort */
            effort: string;
            /** Estimated Calls */
            estimated_calls: number;
            /** Detail */
            detail?: Record<string, never>;
        };
        /** AskRequest */
        AskRequest: {
            /**
             * Question
             * @example Marjı en hızlı daralan ürün hangisi?
             */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Dataset Id */
            dataset_id: string;
            /** Question */
            question: string;
            answer: components["schemas"]["QAAnswer"];
            grounding: components["schemas"]["GroundingOut"];
            telemetry: components["schemas"]["TelemetryOut"];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /** Body_upload_dataset_api_v1_datasets_post */
        Body_upload_dataset_api_v1_datasets_post: {
            /**
             * File
             * Format: binary
             * @description İşlenecek CSV dosyası
             */
            file: string;
            /**
             * Pack
             * @description Rapor tipi (ör. 'sonart-erp'). Boş bırakılırsa başlıklardan tespit edilir.
             */
            pack?: string | null;
        };
        /** DatasetSummary */
        DatasetSummary: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Pack Key */
            pack_key: string;
            /** Pack Title */
            pack_title: string;
            /** Raw Row Count */
            raw_row_count: number;
            /** Clean Row Count */
            clean_row_count: number;
            /** Quarantined Row Count */
            quarantined_row_count: number;
            /** Health Score */
            health_score: number;
            /** Encoding Detected */
            encoding_detected: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EntitiesResponse */
        EntitiesResponse: {
            /** Entity Key */
            entity_key: string;
            /** Entity Label Key */
            entity_label_key: string;
            /** Dimensions */
            dimensions: string[];
            /**
             * Columns
             * @description Kolon adı/etiket/birim -- tablo başlıklarını frontend'e taşır.
             */
            columns: {
                [key: string]: string;
            }[];
            /** Rows */
            rows: Record<string, never>[];
            /**
             * Series Rows
             * @description (kayıt, dönem) bazında uzun tablo -- kayıt detay grafikleri için.
             */
            series_rows: Record<string, never>[];
        };
        /**
         * ErrorResponse
         * @description Tum hatalarin ortak govdesi.
         *
         *     Istemci `code` alanina gore dallanir; mesaj metni degisse bile kirilmaz.
         */
        ErrorResponse: {
            /**
             * Code
             * @example schema_mismatch
             */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: Record<string, never>;
        };
        /**
         * Evidence
         * @description Bir iddianin dayandigi somut sayi.
         */
        Evidence: {
            /**
             * Metric
             * @description Metrigin teknik adi, or. 'son_kapama_ay'.
             */
            metric: string;
            /**
             * Value
             * @description Verilen tablolardaki degerin aynisi.
             */
            value: number;
            /**
             * Unit
             * @description Birim: TL, adet, %, ay, oran, sayi.
             */
            unit: string;
            /**
             * Entity
             * @description Degerin ait oldugu kapsam. Tek bir kayit ise kodu ('U005', 'K011'); bir kategori/depo/platform kirilimi ise o boyutun adi ('Cantalik', 'Yan Depo'); yalnizca portfoyun tamamiysa bos birak. Kirilim degerini bos birakma -- o zaman portfoy geneliyle karisir.
             */
            entity?: string | null;
            /**
             * Period
             * @description Donem, or. '2026-03'.
             */
            period?: string | null;
        };
        /**
         * ExecutiveSummary
         * @description Yonetime hitap eden ust duzey sentez.
         */
        ExecutiveSummary: {
            /**
             * Headline
             * @description Yonetimin ilk okuyacagi tek cumle.
             */
            headline: string;
            /**
             * Situation
             * @description Genel durum: 2-4 cumle, sayiya dayali.
             */
            situation: string;
            /**
             * Period Narrative
             * @description Alti donemin hikayesi: nereden nereye gelindi, kirilma noktalari hangi donemlerde yasandi.
             */
            period_narrative: string;
            /**
             * Top Risks
             * @description En kritik riskler, oncelik sirasiyla.
             */
            top_risks: components["schemas"]["RiskHighlight"][];
            /**
             * Opportunities
             * @description Degerlendirilmesi gereken firsatlar.
             */
            opportunities?: components["schemas"]["RiskHighlight"][];
            /**
             * Strategic Actions
             * @description Yonetim seviyesinde stratejik aksiyonlar.
             */
            strategic_actions: components["schemas"]["Action"][];
        };
        /**
         * GroundingOut
         * @description AI ciktisinin ne kadarinin hesaplanmis veriye dayandigi.
         */
        GroundingOut: {
            /** Total Evidence */
            total_evidence: number;
            /** Verified Evidence */
            verified_evidence: number;
            /** Grounding Ratio */
            grounding_ratio: number;
            /** Issues */
            issues?: Record<string, never>[];
        };
        /** MetricOut */
        MetricOut: {
            /** Metric */
            metric: string;
            /** Label */
            label: string;
            /** Value */
            value: number;
            /** Unit */
            unit: string;
            /** Entity */
            entity?: string | null;
            /** Period */
            period?: string | null;
        };
        /** OverviewResponse */
        OverviewResponse: {
            dataset: components["schemas"]["DatasetSummary"];
            /** Periods */
            periods: string[];
            /** Entity Count */
            entity_count: number;
            /** Headline Metrics */
            headline_metrics: components["schemas"]["MetricOut"][];
            /**
             * Period Rows
             * @description Dönem bazında portföy özeti -- trend grafiklerinin kaynağı.
             */
            period_rows: Record<string, never>[];
            /** Risk Counts By Severity */
            risk_counts_by_severity: {
                [key: string]: number;
            };
            /** Top Risks */
            top_risks: components["schemas"]["RiskOut"][];
        };
        /** PackOut */
        PackOut: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Entity Key */
            entity_key: string;
            /** Period Key */
            period_key: string;
            /** Dimensions */
            dimensions: string[];
            /** Required Columns */
            required_columns: string[];
            /** Risk Rule Count */
            risk_rule_count: number;
            /** Metric Count */
            metric_count: number;
            /** Sample File */
            sample_file: string;
        };
        /**
         * PeriodAnalysis
         * @description Tek bir donemin analizi.
         *
         *     `delta_vs_prev` bilerek zorunlu: modelin her donem icin ayni genel metni
         *     uretmesini engelleyip bir onceki doneme gore *ne degistigini* soylemeye
         *     mecbur birakir. Donemsel farklilasmanin sema tarafindaki garantisi budur.
         */
        PeriodAnalysis: {
            /** Period */
            period: string;
            /**
             * Headline
             * @description Bu donemi tek cumlede ozetleyen baslik.
             */
            headline: string;
            /**
             * Delta Vs Prev
             * @description Bir onceki doneme gore somut olarak ne degisti. Ilk donemde baslangic durumunu tarif et. Genel ifade degil, sayiya dayali fark.
             */
            delta_vs_prev: string;
            /**
             * Dominant Dynamics
             * @description Bu donemi belirleyen dinamikler (verilen listeden secilir).
             */
            dominant_dynamics: string[];
            /**
             * Actions
             * @description Bu doneme ozgu aksiyonlar.
             */
            actions: components["schemas"]["Action"][];
            /**
             * Watch Items
             * @description Henuz aksiyon gerektirmeyen ama izlenmesi gerekenler.
             */
            watch_items?: string[];
        };
        /** PeriodsResponse */
        PeriodsResponse: {
            /** Periods */
            periods: string[];
            /** Rows */
            rows: Record<string, never>[];
            /**
             * Deltas
             * @description Her dönemin bir öncekine göre değişimi ve o dönemde açılan riskler.
             */
            deltas: Record<string, never>[];
            /** Dimension Rows */
            dimension_rows: Record<string, never>[];
        };
        /**
         * QAAnswer
         * @description Serbest soru-cevap yaniti.
         */
        QAAnswer: {
            /**
             * Answer
             * @description Soruya dogrudan, Turkce yanit.
             */
            answer: string;
            /**
             * Evidence
             * @description Yaniti destekleyen, tablolardan alinmis sayilar.
             */
            evidence?: components["schemas"]["Evidence"][];
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "yuksek" | "orta" | "dusuk";
            /**
             * Caveats
             * @description Yanitin sinirlari; veri yetersizse veya soru kapsam disiysa burada belirt.
             */
            caveats?: string[];
        };
        /** QualityIssueOut */
        QualityIssueOut: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Severity */
            severity: string;
            /** Action */
            action: string;
            /** Affected Rows */
            affected_rows: number;
            /** Detail */
            detail: string;
            /** Samples */
            samples?: string[];
        };
        /** QualityReportOut */
        QualityReportOut: {
            /** Raw Row Count */
            raw_row_count: number;
            /** Clean Row Count */
            clean_row_count: number;
            /** Quarantined Row Count */
            quarantined_row_count: number;
            /** Encoding Detected */
            encoding_detected: string;
            /** Encoding Repaired */
            encoding_repaired: boolean;
            /** Health Score */
            health_score: number;
            /** Issues */
            issues: components["schemas"]["QualityIssueOut"][];
        };
        /** RiskHighlight */
        RiskHighlight: {
            /** Entity */
            entity: string;
            /** Title */
            title: string;
            /** Why It Matters */
            why_it_matters: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** RiskOut */
        RiskOut: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Severity */
            severity: string;
            /** Entity */
            entity: string;
            /** Entity Label */
            entity_label: string;
            /** Dimensions */
            dimensions?: {
                [key: string]: string;
            };
            /** Narrative */
            narrative: string;
            /** Recommendation */
            recommendation: string;
            /** Evidence */
            evidence?: components["schemas"]["MetricOut"][];
            /** Financial Impact Tl */
            financial_impact_tl?: number | null;
            /** First Seen Period */
            first_seen_period?: string | null;
        };
        /** RisksResponse */
        RisksResponse: {
            /** Total */
            total: number;
            /** Total Financial Impact Tl */
            total_financial_impact_tl: number;
            /** By Severity */
            by_severity: {
                [key: string]: number;
            };
            /** By Code */
            by_code: {
                [key: string]: number;
            };
            /** Risks */
            risks: components["schemas"]["RiskOut"][];
        };
        /** TelemetryOut */
        TelemetryOut: {
            /**
             * Call Count
             * @default 0
             */
            call_count: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Cache Write Tokens
             * @default 0
             */
            cache_write_tokens: number;
            /**
             * Cache Read Tokens
             * @default 0
             */
            cache_read_tokens: number;
            /**
             * Cache Hit Calls
             * @default 0
             */
            cache_hit_calls: number;
            /**
             * Total Cost Usd
             * @default 0
             */
            total_cost_usd: number;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
        };
        /** UploadResponse */
        UploadResponse: {
            dataset: components["schemas"]["DatasetSummary"];
            quality: components["schemas"]["QualityReportOut"];
            /** Periods */
            periods: string[];
            /** Entity Count */
            entity_count: number;
            /** Risk Count */
            risk_count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    packs_api_v1_packs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackOut"][];
                };
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_datasets_api_v1_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"][];
                };
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya boyutu izin verilen sınırı aşıyor */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_dataset_api_v1_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_api_v1_datasets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya boyutu izin verilen sınırı aşıyor */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_dataset_api_v1_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"];
                };
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya boyutu izin verilen sınırı aşıyor */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_dataset_api_v1_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya boyutu izin verilen sınırı aşıyor */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_quality_api_v1_datasets__dataset_id__quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityReportOut"];
                };
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya boyutu izin verilen sınırı aşıyor */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_overview_api_v1_datasets__dataset_id__overview_get: {
        parameters: {
            query?: {
                /** @description Dönülecek risk sayısı */
                top?: number;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya boyutu izin verilen sınırı aşıyor */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_periods_api_v1_datasets__dataset_id__periods_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeriodsResponse"];
                };
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya boyutu izin verilen sınırı aşıyor */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_entities_api_v1_datasets__dataset_id__entities_get: {
        parameters: {
            query?: {
                /** @description (kayıt, dönem) uzun tablosunu da döndür */
                include_series?: boolean;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitiesResponse"];
                };
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya boyutu izin verilen sınırı aşıyor */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_risks_api_v1_datasets__dataset_id__risks_get: {
        parameters: {
            query?: {
                /** @description Ağırlığa göre filtre, ör. 'kritik' */
                severity?: string | null;
                /** @description Yalnızca bu dönemde açılan riskler */
                period?: string | null;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RisksResponse"];
                };
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya boyutu izin verilen sınırı aşıyor */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analysis_status_api_v1_datasets__dataset_id__analysis_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatusResponse"];
                };
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI servisi istek limitini aştı */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI servisinden geçerli yanıt alınamadı */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI yapılandırılmamış (ANTHROPIC_API_KEY yok) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_analysis_api_v1_datasets__dataset_id__analysis_post: {
        parameters: {
            query?: {
                /** @description Önbelleği yok say ve yeniden üret */
                refresh?: boolean;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI servisi istek limitini aştı */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI servisinden geçerli yanıt alınamadı */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI yapılandırılmamış (ANTHROPIC_API_KEY yok) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ask_api_v1_datasets__dataset_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI servisi istek limitini aştı */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI servisinden geçerli yanıt alınamadı */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI yapılandırılmamış (ANTHROPIC_API_KEY yok) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    download_report_api_v1_datasets__dataset_id__report_pdf_get: {
        parameters: {
            query?: {
                /** @description Önbellekteki AI analizini rapora dahil et (yeni çağrı yapmaz) */
                include_ai?: boolean;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description İstek geçersiz (bilinmeyen rapor tipi, hatalı parametre) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kayıt bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dosya işlenemedi ya da doğrulama hatası */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Beklenmeyen hata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
